# Generated by Django 3.2.12 on 2022-06-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_expiration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchanged',
            name='sent_expired_mail_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='passwordchanged',
            name='sent_expires_soon_mail_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
